version: '3.8'

networks:
  api_gateway:
  internal_services:
  accounts:
  cryptocurrencies:

services:
  accounts-mongodb:
    container_name: cryptocurrency-viewer-accounts-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_ACCOUNTS_DATABASE}
    volumes:
      - cryptocurrency-viewer-accounts-mongodb:/data/db
    command: mongod --port ${MONGODB_ACCOUNTS_PORT}
    restart: unless-stopped
    networks:
      - accounts

  cryptocurrencies-mongodb:
    container_name: cryptocurrency-viewer-cryptocurrencies-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_CRYPTOCURRENCIES_DATABASE}
    volumes:
      - cryptocurrency-viewer-cryptocurrencies-mongodb:/data/db
    command: mongod --port ${MONGODB_CRYPTOCURRENCIES_PORT}
    restart: unless-stopped
    networks:
      - cryptocurrencies

  api-gateway:
    container_name: cryptocurrency-viewer-api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    ports:
      - ${API_GATEWAY_PORT:-50000}:${API_GATEWAY_PORT:-50000}
      - ${API_GATEWAY_DEBUGGER_PORT:-9229}:${API_GATEWAY_DEBUGGER_PORT:-9229}
    restart: unless-stopped
    networks:
      - api_gateway
      - internal_services
      - accounts
      - cryptocurrencies

  accounts-service:
    container_name: cryptocurrency-viewer-accounts-service
    build:
      context: .
      dockerfile: ./apps/account-service/Dockerfile
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      - accounts-mongodb
    restart: unless-stopped
    networks:
      - internal_services
      - accounts

  cryptocurrencies-service:
    container_name: cryptocurrency-viewer-cryptocurrencies-service
    build:
      context: .
      dockerfile: ./apps/cryptocurrency-service/Dockerfile
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      - cryptocurrencies-mongodb
    restart: unless-stopped
    networks:
      - internal_services
      - cryptocurrencies

  # frontend:
  #   container_name: cryptocurrency-viewer-frontend
  #   build:
  #     context: .
  #     dockerfile: ./apps/frontend/Dockerfile
  #     target: development
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - ${FRONTEND_PORT:-5173}:${FRONTEND_PORT:-5173}
  #   command: ["yarn", "start:dev", "--port", "${FRONTEND_PORT:-5173}"]
  #   restart: unless-stopped
  #   networks:
  #     - api_gateway

volumes:
  cryptocurrency-viewer-accounts-mongodb:
  cryptocurrency-viewer-cryptocurrencies-mongodb: