name: 'cryptocurrency-service-pull-request-checks'

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/cryptocurrency-service/**"
      - ".github/workflows/cryptocurrency-service-pull-request-checks.yml"

defaults:
  run:
    working-directory: ./apps/cryptocurrency-service

jobs:
  pull-request-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn install --silent --frozen-lockfile

    - name: Build @cryptocurrency-viewer/testing
      run: cd packages/testing && yarn install --silent --frozen-lockfile && yarn build

    - name: Run tests
      run: yarn test:ci